"""
Script to build the improved notebook with all cells
"""
import json

# Load existing notebook
with open('monthly_news_review_IMPROVED.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Parse Telegram channels cell
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "all_posts = []\n",
        "\n",
        "async def parse_channels():\n",
        "    \"\"\"Parse messages from all configured channels\"\"\"\n",
        "    async with TelegramClient(session_name, api_id, api_hash) as client:\n",
        "        for channel in tqdm(channel_usernames, desc=\"Parsing channels\"):\n",
        "            try:\n",
        "                async for message in client.iter_messages(channel, offset_date=end_date):\n",
        "                    if message.date < start_date:\n",
        "                        break\n",
        "                    if message.text:\n",
        "                        all_posts.append({\n",
        "                            \"id\": message.id,\n",
        "                            \"date\": message.date,\n",
        "                            \"text\": message.text,\n",
        "                            \"channel\": channel\n",
        "                        })\n",
        "            except Exception as e:\n",
        "                print(f\"  ⚠️ Error parsing {channel}: {e}\")\n",
        "                continue\n",
        "\n",
        "# Run parsing\n",
        "await parse_channels()\n",
        "\n",
        "# Create DataFrame\n",
        "df = pd.DataFrame(all_posts)\n",
        "df['date'] = pd.to_datetime(df['date'])\n",
        "df_filtered = df[(df['date'] >= start_date) & (df['date'] <= end_date)]\n",
        "\n",
        "print(f\"\\n✅ Collected {len(df_filtered):,} posts from {len(channel_usernames)} channels\")"
    ]
})

# Utility functions cell
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "def estimate_tokens(text):\n",
        "    \"\"\"Rough estimate: 1 token ≈ 4 characters for Russian\"\"\"\n",
        "    return len(text) // 4\n",
        "\n",
        "\n",
        "def truncate_summaries(summaries, max_tokens=100000):\n",
        "    \"\"\"Keep only most recent summaries within token limit\"\"\"\n",
        "    combined = \"\"\n",
        "    kept_summaries = []\n",
        "\n",
        "    for summary in reversed(summaries):\n",
        "        test_combined = f\"- {summary}\\n\" + combined\n",
        "        if estimate_tokens(test_combined) > max_tokens:\n",
        "            break\n",
        "        combined = test_combined\n",
        "        kept_summaries.insert(0, summary)\n",
        "\n",
        "    if len(kept_summaries) < len(summaries):\n",
        "        print(f\"⚠️ Truncated from {len(summaries)} to {len(kept_summaries)} summaries\")\n",
        "\n",
        "    return kept_summaries\n",
        "\n",
        "\n",
        "def save_checkpoint(relevant_summaries, total_posts):\n",
        "    \"\"\"Save intermediate results\"\"\"\n",
        "    checkpoint_file = f\"checkpoint_{start_date.strftime('%Y%m')}.json\"\n",
        "    checkpoint_data = {\n",
        "        'saved_at': datetime.now().isoformat(),\n",
        "        'summaries': relevant_summaries,\n",
        "        'total_posts': total_posts,\n",
        "        'relevant_count': len(relevant_summaries)\n",
        "    }\n",
        "    with open(checkpoint_file, 'w', encoding='utf-8') as f:\n",
        "        json.dump(checkpoint_data, f, ensure_ascii=False, indent=2)\n",
        "    print(f\"💾 Checkpoint saved: {checkpoint_file}\")\n",
        "    return checkpoint_file\n",
        "\n",
        "\n",
        "def load_checkpoint():\n",
        "    \"\"\"Load checkpoint if exists\"\"\"\n",
        "    checkpoint_file = f\"checkpoint_{start_date.strftime('%Y%m')}.json\"\n",
        "    if Path(checkpoint_file).exists():\n",
        "        with open(checkpoint_file, 'r', encoding='utf-8') as f:\n",
        "            checkpoint = json.load(f)\n",
        "        print(f\"✅ Loaded from checkpoint: {checkpoint['relevant_count']} summaries\")\n",
        "        return checkpoint['summaries']\n",
        "    return None\n",
        "\n",
        "\n",
        "@retry.Retry(\n",
        "    predicate=retry.if_exception_type(\n",
        "        exceptions.ResourceExhausted,\n",
        "        exceptions.ServiceUnavailable,\n",
        "    ),\n",
        "    initial=1.0,\n",
        "    maximum=10.0,\n",
        "    multiplier=2.0,\n",
        "    timeout=60.0,\n",
        ")\n",
        "def generate_with_retry(model, prompt):\n",
        "    \"\"\"Generate content with automatic retry\"\"\"\n",
        "    return model.generate_content(prompt)\n",
        "\n",
        "\n",
        "print(\"✅ Utility functions loaded\")"
    ]
})

# Prompt functions cell
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "def get_improved_prompt_individual(text):\n",
        "    return f\"\"\"Ты - аналитик российского рынка FMCG и e-commerce. Твоя задача: определить, релевантна ли новость для ежемесячного обзора рынка и извлечь ключевые факты.\n",
        "\n",
        "ОБЛАСТЬ АНАЛИЗА (FMCG/e-commerce РФ 2024-2025):\n",
        "\n",
        "**Категории продуктов:**\n",
        "- Напитки: лимонады, кола, энергетики, холодный чай\n",
        "- Снеки: чипсы, закуски\n",
        "- Молочная продукция\n",
        "- Детское питание\n",
        "\n",
        "**Бренды и компании:**\n",
        "- Производители: Nestle (детское питание), Черкизово, Мираторг, Эфко, Балтика\n",
        "- Новые бренды: Добрый Cola, Вкусно и точка, Stars Coffee, азиатские бренды\n",
        "- Маркетплейсы: Ozon, Wildberries (WB), Яндекс Маркет (ЯМ), СберМегаМаркет\n",
        "- Ритейл: X5 Group (Пятёрочка, Перекрёсток), Магнит, Лента, ВкусВилл\n",
        "\n",
        "**Ключевые темы:**\n",
        "- Импортозамещение и локализация производства\n",
        "- Параллельный импорт\n",
        "- СТМ (собственные торговые марки)\n",
        "- Омниканальность и онлайн-торговля\n",
        "- Ценообразование и промо\n",
        "\n",
        "**ИСКЛЮЧИТЬ:**\n",
        "- B2B-сервисы (не для конечных потребителей)\n",
        "- Финансовые услуги (банки, кредиты, инвестиции)\n",
        "- Автомобили и запчасти\n",
        "- Электроника и бытовая техника\n",
        "- HR и вакансии\n",
        "\n",
        "**ИНСТРУКЦИЯ:**\n",
        "\n",
        "Если новость релевантна:\n",
        "- Извлеки ключевую информацию: КТО (компания/бренд), ЧТО (событие), ЦИФРЫ (если есть)\n",
        "- Напиши краткую суть в 2-3 предложениях\n",
        "- Используй конкретные названия и числа\n",
        "\n",
        "Если новость НЕ релевантна:\n",
        "- Напиши только: \"НЕРЕЛЕВАНТНО\"\n",
        "\n",
        "**НОВОСТЬ:**\n",
        "{text}\n",
        "\n",
        "**ТВОЙ ОТВЕТ:**\"\"\"\n",
        "\n",
        "\n",
        "def get_improved_prompt_final(summaries, start_date, num_channels, num_summaries):\n",
        "    return f\"\"\"Ты - старший аналитик российского рынка FMCG и e-commerce. Составь ежемесячный аналитический обзор для руководства компании.\n",
        "\n",
        "**ЦЕЛЕВАЯ АУДИТОРИЯ:** Топ-менеджмент (CEO, CMO, Head of Sales)\n",
        "**ТОН:** Деловой, лаконичный, фокус на цифрах и бизнес-импликациях\n",
        "**ПЕРИОД:** {start_date.strftime('%B %Y')}\n",
        "**ИСТОЧНИК ДАННЫХ:** {num_summaries} релевантных новостей из {num_channels} отраслевых каналов\n",
        "\n",
        "---\n",
        "\n",
        "**ЗАДАЧА:** Структурированный отчет с фокусом на:\n",
        "- ✅ Повторяющиеся сигналы (тренды, а не единичные события)\n",
        "- ✅ Количественные данные (цифры, проценты, суммы)\n",
        "- ✅ Системные изменения (влияние на рынок)\n",
        "- ❌ Маркетинговые анонсы без бизнес-контекста\n",
        "- ❌ Единичные новости без влияния на индустрию\n",
        "\n",
        "---\n",
        "\n",
        "**СТРУКТУРА ОТЧЕТА (10 РАЗДЕЛОВ):**\n",
        "\n",
        "**1. Общее состояние рынка**\n",
        "Основные макротренды месяца: потребительский спрос, ценообразование, конкурентная среда (2-3 ключевых вывода)\n",
        "\n",
        "**2. Финансовые результаты**\n",
        "Компании, опубликовавшие отчетность → **[Компания]:** выручка, прибыль, GMV, доля e-commerce, динамика vs прошлый период\n",
        "\n",
        "**3. Маркетплейсы**\n",
        "Ozon, Wildberries, Яндекс Маркет, СберМегаМаркет → **[Компания]:** изменения комиссий, логистика, новые сервисы, ключевые метрики\n",
        "\n",
        "**4. Омниканальный ритейл**\n",
        "X5, Магнит, Лента, ВкусВилл → **[Компания]:** цифровая трансформация, доставка, приложения, интеграция онлайн/офлайн\n",
        "\n",
        "**5. Агрегаторы и доставка**\n",
        "Яндекс Еда, Деливери, Т-банк (Купер) → **[Компания]:** тарифы, технологические новинки, география, партнерства\n",
        "\n",
        "**6. Производители FMCG**\n",
        "Бренды и фабрики → **[Компания]:** новые продукты, ценообразование, маркетинговые кампании, проблемы поставок\n",
        "\n",
        "**7. Новинки и инновации**\n",
        "Новые запуски → **[Бренд/продукт]:** описание, целевая аудитория, потенциальное влияние на рынок\n",
        "\n",
        "**8. Цепочки поставок**\n",
        "Проблемы и решения → **[Проблема/компания]:** суть, масштаб, способы решения, влияние на цены\n",
        "\n",
        "**9. Регулирование**\n",
        "Законы, ФАС, инициативы госорганов → **[Событие]:** суть изменений, кого затрагивает, сроки внедрения, бизнес-эффект\n",
        "\n",
        "**10. Прогноз на следующий месяц**\n",
        "Ожидаемые тренды и риски (2-3 предложения)\n",
        "\n",
        "---\n",
        "\n",
        "**ПРАВИЛА ОФОРМЛЕНИЯ:**\n",
        "- Используй **жирный шрифт** для названий компаний и брендов\n",
        "- Обязательно указывай цифры и даты\n",
        "- Максимум 3 предложения на каждый пункт\n",
        "- Если по разделу нет значимых новостей, напиши: \"*Значимых изменений не зафиксировано*\"\n",
        "- Избегай общих фраз типа \"продолжается развитие\" - конкретика и факты\n",
        "\n",
        "---\n",
        "\n",
        "**ИСХОДНЫЕ ДАННЫЕ (НОВОСТИ):**\n",
        "\n",
        "{summaries}\n",
        "\n",
        "---\n",
        "\n",
        "**АНАЛИТИЧЕСКИЙ ОТЧЕТ:**\"\"\"\n",
        "\n",
        "\n",
        "print(\"✅ Improved prompts loaded\")"
    ]
})

# Stage 1 filtering cell
notebook["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Try to load from checkpoint first\n",
        "checkpoint_summaries = load_checkpoint()\n",
        "\n",
        "if checkpoint_summaries is not None:\n",
        "    print(f\"📂 Using checkpoint data: {len(checkpoint_summaries)} summaries\")\n",
        "    relevant_summaries = checkpoint_summaries\n",
        "else:\n",
        "    print(f\"\\n🔍 Starting analysis of {len(df_filtered)} posts (Stage 1: Filtering)...\")\n",
        "    relevant_summaries = []\n",
        "    error_count = 0\n",
        "\n",
        "    for index, row in tqdm(df_filtered.sort_values(by='date').iterrows(),\n",
        "                           total=len(df_filtered),\n",
        "                           desc=\"Filtering posts\"):\n",
        "\n",
        "        prompt_individual = get_improved_prompt_individual(row['text'])\n",
        "\n",
        "        try:\n",
        "            response = generate_with_retry(model_filter, prompt_individual)\n",
        "\n",
        "            if not response.text or len(response.text.strip()) < 10:\n",
        "                continue\n",
        "\n",
        "            if \"НЕРЕЛЕВАНТНО\" not in response.text.upper():\n",
        "                relevant_summaries.append(response.text.strip())\n",
        "\n",
        "            time.sleep(0.5)\n",
        "\n",
        "        except exceptions.ResourceExhausted:\n",
        "            print(f\"\\n  ⚠️ Rate limit reached, pausing 10 seconds...\")\n",
        "            time.sleep(10)\n",
        "            error_count += 1\n",
        "            continue\n",
        "\n",
        "        except Exception as e:\n",
        "            print(f\"\\n  ❌ Error: {e}\")\n",
        "            error_count += 1\n",
        "            continue\n",
        "\n",
        "    print(f\"\\n✅ Stage 1 complete!\")\n",
        "    print(f\"   Total posts: {len(df_filtered):,}\")\n",
        "    print(f\"   Relevant: {len(relevant_summaries):,} ({len(relevant_summaries)/len(df_filtered)*100:.1f}%)\")\n",
        "    print(f\"   Errors: {error_count}\")\n",
        "\n",
        "    if len(relevant_summaries) > 0:\n",
        "        save_checkpoint(relevant_summaries, len(df_filtered))"
    ]
})

# Save the notebook
with open('monthly_news_review_IMPROVED.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=2)

print(f"✅ Built improved notebook with {len(notebook['cells'])} cells")
